#!/usr/bin/env python3
"""Check that the C++ tables generated from Go still say what Go says.

Two tables in cpp/src are not written by hand. Each is generated by a small Go
program under cpp/tools/_gen that asks Go itself, code point by code point:

    width_table.cpp   internal/render's VisibleWidth
    print_table.cpp   strconv.IsPrint

WHY GO GENERATES THEM. The thing being matched is the Go binary's behaviour, and
that rests on Go's own Unicode tables. Python's unicodedata is a different
Unicode version, so a table written from it would agree almost everywhere and
be wrong somewhere nobody tested. The directory starts with an underscore, so the
Go toolchain's ./... never builds, vets or lints the generators.

    python3 cpp/tools/check_tables.py            fails when a table has drifted
    python3 cpp/tools/check_tables.py --write    regenerates both

Generator output is passed through clang-format with the jig's style before it
is compared or written, so a regenerated table is already format-clean.

Run from the repository root.
"""

import argparse
import difflib
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
STYLE = ROOT / "config" / "cpp" / "clang-format.yaml"

TABLES = {
    "cpp/src/width_table.cpp": "cpp/tools/_gen/widthgen/main.go",
    "cpp/src/print_table.cpp": "cpp/tools/_gen/printgen/main.go",
}


def generate(generator: str, target: str) -> str:
    """The table a generator writes, formatted as the gate formats C++."""
    raw = subprocess.run(
        ["go", "run", generator],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return subprocess.run(
        ["clang-format", f"--style=file:{STYLE}", f"--assume-filename={target}"],
        cwd=ROOT,
        input=raw,
        check=True,
        capture_output=True,
        text=True,
    ).stdout


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the tables")
    args = parser.parse_args(argv)

    drifted = 0
    for target, generator in TABLES.items():
        fresh = generate(generator, target)
        path = ROOT / target
        if args.write:
            path.write_text(fresh)
            print(f"wrote {target}")
            continue
        current = path.read_text() if path.exists() else ""
        if current == fresh:
            print(f"same  {target}")
            continue
        drifted += 1
        print(f"DRIFTED  {target}: regenerate with --write")
        diff = difflib.unified_diff(
            current.splitlines(), fresh.splitlines(), "committed", "generated", lineterm=""
        )
        for line in list(diff)[:40]:
            print(f"    {line}")
    return 1 if drifted else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
